[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/",
    "@account-abstraction/contracts=lib/account-abstraction/contracts/",
    "@foundry-devops/src=lib/foundry-devops/src/",
    "@foundry-era-contracts/src=lib/foundry-era-contracts/src/",
]

fs_permissions = [{ access = "read", path = "./broadcast" }]
via-ir = true
is-system = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
